### ISSUE TITLE
Unicode implementation uses out-of-range literals.

### ISSUE THREAD

**Issue by shepmaster** [avr-rust/rust#100]
Whatever this fix is, it can probably be upstreamed without the rest of AVR.

```
warning: literal out of range for usize
  --> /.../libcore/src/unicode/bool_trie.rs:48:23
   |
48 |         } else if c < 0x10000 {
   |                       ^^^^^^^
   |
   = note: #[warn(overflowing_literals)] on by default
   = note: the literal `0x10000` (decimal `65536`) does not fit into an `usize` and will become `0usize`
```

**Comment by shepmaster** [comment]
The actual arrays are small, so this can probably be solved with some judicious sizes and casts.

**Comment by kitling** [comment]
Seems like `c < 0x10000` would be equivilant to `c <= 0xFFFF`, which would fix the issue?

**Comment by kitling** [comment]
So I actually took a look at the code now, and I understand a bit more what the actual issue is. Perhaps usize should just be changed to u32 (or u64?) instead of usize because of platforms where usize is less that u32.

**Comment by shepmaster** [comment]
> When you say "compiler should just give a warning" do you mean something like "conditional will never be false"?

Oh, I was thinking that if the compiler could tell that:

1. It was a `<` comparison
1. The value was only out of range by 1

Then it could suggest changing to `<=`. It's a very silly thing, but Rust error messages are usually good. ;-)

**Comment by shepmaster** [comment]
> because of platforms where usize is less that u32.

Like AVR, where it's 16 bit 😇 

That sounds like my original idea, which should be a reasonable fallback. I think your idea of adjusting the literal is a cleaner alternative if it works.

**Comment by kitling** [comment]
That won't properly work because the full range of unicode requires 32 bits to express. There is an `else` statement after the `else if` we're working with. This really should work with 32bits at minimum.

**Comment by shepmaster** [comment]
> This really should work with 32bits at minimum.

then yeah, changing from `usize` to `u32` and doing the needed casts at the right point makes the most sense.

**Comment by dylanmckay** [comment]
I've had similar problems with using `bindgen` with AVR headers because `enum`s are represented as `usize = u16`, which is too small to cover a lot of discriminators.

**Comment by crlf0710** [comment]
Now that `c` is converted to u32 instead of usize, i wonder if this issue can be closed now?
https://github.com/avr-rust/rust/blob/avr-support/src/libcore/unicode/bool_trie.rs#L45
