### ISSUE TITLE
Add information about how to build the libcore in the readme

### ISSUE THREAD

**Issue by FabienTregan** [avr-rust/rust#119]
It would be great to add a link to instruction for manually compiling the libcore as it is not abvious for people who don't know much about rust and want to learn rust on an arduino.

(thank you for your amazing work !)

**Comment by FabienTregan** [comment]
Update : I understood my error, the `XARGO_RUST_SRC` was not right, I'll propose a PR to make the information I missunderstood in the readme easyer to get.

**Comment by dylanmckay** [comment]
I've merged the documentation fix, thanks @FabienTregan!
