### ISSUE TITLE
Unit tests regressions!

### ISSUE THREAD

**Issue by carlos4242** [avr-rust/rust#134]
I've just run the unit tests on avr-rust-2019-01-18 and I'm getting regressions?

Testing Time: 2.56s
********************
Failing Tests (4):
    LLVM :: CodeGen/AVR/call.ll
    LLVM :: CodeGen/AVR/directmem.ll
    LLVM :: CodeGen/AVR/div.ll
    LLVM :: CodeGen/AVR/rem.ll

  Expected Passes    : 117
  Expected Failures  : 3
  Unexpected Failures: 4

**Comment by carlos4242** [comment]
These are all fixed by avr-rust/llvm PR #10.

**Comment by carlos4242** [comment]
LABEL AS: has local patch

**Comment by hercek** [comment]
How do you run the unit tests (except running them for each file manually)?
`llvm-lit` does not work on my build. It does not have python variable `llvm_config` defined probably becase `rust/src/llvm/test/lit.site.cfg.py.in` is not processed to `lit.site.cfg.py`.

**Comment by carlos4242** [comment]
When you build llvm you’ll have a bin directory where llc, opt, etc. are located. In there is llvm-lit.

Run it then pass the test directory.

For example in my set up, I have the llvm source code in ~/llvm. The build is in a sub folder ~/llvm/build. To run lit I would do:

~/llvm/build/bin/llvm-lit ~/test/CodeGen/AVR

Which runs all tests. Or append a single test.

**Comment by hercek** [comment]
Thanks. That is it. When you let rust build system to build llvm then it does not build `llvm-lit` and trying to run it from `build/utils/llvm-lit` does not work as I described before.

**Comment by dylanmckay** [comment]
Since fixed in LLVM trunk.
