### ISSUE TITLE
Make exits with error because rust/doc/book not found

### ISSUE THREAD

**Issue by juliangaal** [avr-rust/rust#138]
Hi, with your script provided, make exits with 

> No such file or directory: ../rust/doc/book 

My system: Ubuntu 16.04

I fixed this by cloning this fork with the `--recursive` option to download all submodules from the start. I'm not sure If this is an error on my side, or one in the example script.

**Comment by dylanmckay** [comment]
Usually Rust's build scripts will automatically fetch/update all submodules when they are invoked.

I agree that it's perhaps a better suggestion to explicitly clone the repo with `--recursive`.

I have added that flag to the example script in the README in /a51b762263546e1388fbce5020913a436fdb5c82.

Thanks for the bug report @juliangaal
