### ISSUE TITLE
Configure Clang Version

### ISSUE THREAD

**Issue by travisgalloway** [avr-rust/rust#15]
The Clang version in Configure fails for the latest version of Clang.

`        if [ -n "$CFG_OSX_CLANG_VERSION" ]
        then
            case $CFG_OSX_CLANG_VERSION in
                (7.0*)`

Should read:

`        if [ -n "$CFG_OSX_CLANG_VERSION" ]
        then
            case $CFG_OSX_CLANG_VERSION in
                (7.*)`

**Comment by dylanmckay** [comment]
I think this has been fixed in upstream Rust. I can successfully build with `clang` 8.0
