### ISSUE TITLE
Missing compiler-rt commit

### ISSUE THREAD

**Issue by tbelaire** [avr-rust/rust#17]
It looks like there's a commit in compiler-rt which isn't published?  I can't fetch the submodule.
```
error: no such remote ref 91f0fe0e367edd404ec5576bab070abb92333db9
Fetched in submodule path 'src/compiler-rt', but it did not contain 91f0fe0e367edd404ec5576bab070abb92333db9. Direct fetching of that commit failed.
```

**Comment by dylanmckay** [comment]
@shepmaster do you know about this?

@tbelaire could you do a `git remote -v` inside the `src/compiler-rt` directory?

**Comment by shepmaster** [comment]
Ugh, yeah, that's my fault. And unfortunately, it looks like I pushed it to `avr-llvm/compiler-rt` instead of `avr-rust/compiler-rt`... too many forks. Is that going to screw up the normal AVR work, @dylanmckay ?

**Comment by shepmaster** [comment]
Overall, the whole story around compiler-rt is less-than-ideal. Rust upstream is going to try to avoid the whole mess around building it, for example - rust-lang/rust#34400.

**Comment by dylanmckay** [comment]
It won't mess anything up, I haven't even been checking it out recently lol

**Comment by dylanmckay** [comment]
No longer an issue as far as I can tell.
