### ISSUE TITLE
Rework C-ABI translation

### ISSUE THREAD

**Issue by shepmaster** [avr-rust/rust#30]
Looks like f0636b61c7f84962a609e831760db9d77f4f5e14 rewrote how all of the layout / alignment / LLVM type stuff is handled (*insert handwaving here*). I've had to completely comment it out to proceed with compilation, but I'm pretty sure any resulting compiler will be inoperable.

@dylanmckay I can push up (yet another) branch with this WIP if you'd be able to do that brain-thinking-thing you know how do to?

**Comment by dylanmckay** [comment]
> @dylanmckay I can push up (yet another) branch with this WIP if you'd be able to do that brain-thinking-thing you know how do to?

Might as well give it a go :)

**Comment by shepmaster** [comment]
Hurrah! https://github.com/avr-rust/rust/tree/avr-support-4.0-abi-hack

**Comment by dylanmckay** [comment]
I think I got it working at #33 

The build succeeds locally, and it successfully converts a small Rust program to assembly.

**Comment by shepmaster** [comment]
Cool. I've merged, removed the commenting / revert of commenting, rebased on latest latest Rust, and am doing a fresh build. If it compiles, I'm pushing to `avr-support` and we can run from there.
