### ISSUE TITLE
Collection of all bugfixes required to get everything working

### ISSUE THREAD

**Issue by dylanmckay** [avr-rust/rust#40]
This issue is used for listing all bugfixes that we need to get into the LLVM fork before the compiler is usable.

This list will be added to over time.

* Invalid machine code in .elf file (#39)
* LDDWRdYQ - Bad machine code: Using an undefined physical register (#32)
* Assertion failed: (DstReg != SrcReg && "SrcReg and DstReg cannot be the same") (#27)

**Comment by shepmaster** [comment]
I was gonna try and use https://github.com/avr-rust/rust/issues?q=is%3Aissue+is%3Aopen+label%3Ahas-llvm-commit for that.

**Comment by dylanmckay** [comment]
I see, that's a better idea. I'll close this.

**Comment by shepmaster** [comment]
I added that search to #29
