### ISSUE TITLE
LPMWRdZ et al. should be marked to clobber the Z register?

### ISSUE THREAD

**Issue by gergoerdi** [avr-rust/rust#59]
Since `LPMW*` is expanded into `lpm dst, Z+; lpm dst+1, Z`, shouldn't we mark it to be clobbering `Z`?

**Comment by dylanmckay** [comment]
I'd definitely think it should, I'm surprised it isn't already. That means that we could clobber Z sometimes when LPMW is used.

**Comment by dylanmckay** [comment]
Fixed upstream in [r307056](http://llvm.org/viewvc/llvm-project?view=revision&revision=307056) and cherry-picked in ab10f360511f413f778e81a6097cf4ae533d78cb.
