### ISSUE TITLE
Inline weirdness

### ISSUE THREAD

**Issue by dsvensson** [avr-rust/rust#67]
The following code ported from avr-libc for dealing with crude delays works as long as it's not inlined. Well, it doesn't work that well as it's timing sensitive and needs inlining, but yeah.. I hope I've [ported it correctly](http://www.nongnu.org/avr-libc/user-manual/delay__basic_8h_source.html), but the real question is hopefully why it breaks if I allow it to be inlined? 

```
#[inline(never)]
pub fn _delay_loop_2(count: u16) {
    unsafe {
        asm!("1: sbiw $0, 1
                 brne 1b"
             : : "r"(count))
    }
}
```
I see here that I have `"r"(count)` in this paste, I've tried `"w"(count)` as well and it emits the same code. My understanding around this is far from complete, but . r24 and r25 together seems to contain what it should: 0x190, or 400.

Here's with "r":
```
000000c4 <_ZN5hello13_delay_loop_217h11d5865208df3b16E>:
  c4:   80 e9           ldi     r24, 0x90       ; 144
  c6:   91 e0           ldi     r25, 0x01       ; 1
  c8:   01 97           sbiw    r24, 0x01       ; 1
  ca:   f1 f7           brne    .-4             ; 0xc8 <_ZN5hello13_delay_loop_217h11d5865208df3b16E+0x4>
  cc:   08 95           ret
```

And here's with "w":
```
000000c4 <_ZN5hello13_delay_loop_217h11d5865208df3b16E>:
  c4:   80 e9           ldi     r24, 0x90       ; 144
  c6:   91 e0           ldi     r25, 0x01       ; 1
  c8:   01 97           sbiw    r24, 0x01       ; 1
  ca:   f1 f7           brne    .-4             ; 0xc8 <_ZN5hello13_delay_loop_217h11d5865208df3b16E+0x4>
  cc:   08 95           ret
```

Removing inline, or setting it to always, yields this error:
```
   Compiling hello v0.1.0 (file:///home/daniel/Development/avr/hello)
error: <inline asm>:1:10: error: invalid operand for instruction
        1: sbiw r18, 1
                ^

  --> src/main.rs:41:9
   |
41 | /         asm!("1: sbiw $0, 1
42 | |                  brne 1b"
43 | |              : : "r"(count))
   | |____________________________^

error: <inline asm>:1:10: error: invalid operand for instruction
        1: sbiw r18, 1
                ^

  --> src/main.rs:41:9
   |
41 | /         asm!("1: sbiw $0, 1
42 | |                  brne 1b"
43 | |              : : "r"(count))
   | |____________________________^

error: aborting due to 2 previous errors

error: Could not compile `hello`.

To learn more, run the command again with --verbose.
```

To get to this point I stumbled across a lot of ways where I could compile code, without getting any of the assembly generated. Just an empty 'ret' instruction.

**Comment by dsvensson** [comment]
Adding "volatile" as an option to asm!() makes it compile. The code doesn't look completely correct though, as it will consume the counter parameter which will never be restored, but that should be fixable. I'll look into this tonight, maybe the issue can be closed.

**Comment by dsvensson** [comment]
After much bruteforcing this seems like a workable solution

```
// http://www.nongnu.org/avr-libc/user-manual/group__util__delay__basic.html
#[inline(always)]
pub fn _delay_loop_2(count: u16) {
    unsafe {
        let mut __count = count;
        asm!("1: sbiw $0, 1
                 brne 1b"
             : "=w"(__count)
             : "0"(__count)
             :
             : "volatile")
    }
}
```

So this issue should be closed. But the question is if I should open tickets about all the weirdness that accepted (when building via xargo, rustc rejected some of the more broken syntax) my faulty asm!() usage, or is that a generic rust issue?

**Comment by dylanmckay** [comment]
I think this might be because SBIW only accepts the top 4 GPR register pairs (there are a few instructions which do this) and the `r` constraint represents any register and so the compiler has no problem allocating `count` to `r18` which then errors out when used in `sbiw` because it isn't a top four gpr pair.

You might need to use a more specific constraint.

It is probably just chance that the online code happens to allocate registers that aren't in the top four pairs, whereas the non inlined version does.

**Comment by dylanmckay** [comment]
*inline

**Comment by dylanmckay** [comment]
I have a feeling that gcc would do this too, unless it was pretty smart about looking through inline assembly and allocating outside variables accordingly

**Comment by dsvensson** [comment]
The problem was that asm!() swallowed bad syntax without emitting any warnings. It works correctly now that I've figured out how to write what I intend it to do.
