### ISSUE TITLE
Investigate writing C bindings to avr-libc

### ISSUE THREAD

**Issue by dylanmckay** [avr-rust/rust#88]
It _may_ be worthwhile creating a crate that simply binds to avr-libc.

That way our users can get functionality without RIIR.

I am slightly hesitant to do this because I dream of an all-Rust ecosystem, but we should definitely keep it in mind.

**Comment by binder-lukas** [comment]
Would rellay like it, need to use some functions from the avr/*.h and struggle at the moment get it running

**Comment by dylanmckay** [comment]
[Your wish is my command](https://github.com/avr-rust/libc)
